### ISSUE TITLE
Pipedream: read ECONNRESET

### ISSUE THREAD

**Issue by fitwist** [kirill-markin/split-documents-upload-to-pinecone#2]
The Pipedream automation is configured and deployed (Slack, OpenAI, Pinecone API keys added), but each message in a selected Slack chat gives me an error: 

```
read ECONNRESET

DETAILS
    at null.__node_internal_captureLargerStackTrace (internal/errors.js:412:5)
    at null.__node_internal_errnoException (internal/errors.js:542:12)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
```

Previous steps are being completed in every attempt.

<img width="1792" alt="Снимок экрана 2023-06-14 в 16 50 28" src="https://github.com/kirill-markin/split-documents-upload-to-pinecone/assets/22573148/b379c643-9b31-4390-b0f6-7dbaf389b7c8">

**Comment by fitwist** [comment]
It turned out I missed one letter in Pinecone configuration / project ID.
Error traceback is non-obvious. Hope it helps anybody.
